AdventureWorksSales.Web/Models/ProductCategoryModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AdventureWorksSales.Web.Models {
    public class ProductCategoryModel {
        public virtual int ProductCategoryID { get; set; } = 0;
        public virtual string Name { get; set; } = string.Empty;
        public virtual DateTime ModifiedDate { get; set; } =DateTime.Now;

    }
}

AdventureWorksSales.Web/Models/SalesAnalysisModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AdventureWorksSales.Web.Models {
    public class SalesAnalysisModel {
        public virtual UInt32 TotalOrders{ get; set; } =0;
        public virtual  decimal HighestLineTotal { get; set; } = 0;
        public virtual  decimal FrontBrakesSalesTotal { get; set; } = 0;
    }
}

AdventureWorksSales.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.SqlClient;
using AdventureWorksSales.Web.Models;

namespace AdventureWorksSales.Web.Controllers
{
    public class HomeController : Controller
    {
        
        public ActionResult Index()
        {
            dbObj conObj = new dbObj();
            SalesAnalysisModel salesAnalysisModel=new SalesAnalysisModel();
            try { 
                conObj.cmdObj=new SqlCommand("SELECT SUM(OrderQty) AS Qtot FROM SalesOrder",new SqlConnection(dbObj.conStr)); 
                conObj.cmdObj.Connection.Open();
                conObj.drObj=conObj.cmdObj.ExecuteReader();
                if (conObj.drObj.Read()) salesAnalysisModel.TotalOrders = Convert.ToUInt32(conObj.drObj["Qtot"]);
                conObj.cmdObj.Dispose();
                conObj.cmdObj=new SqlCommand("SELECT MAX(LineTotal) AS Linetot FROM SalesOrder",new SqlConnection(dbObj.conStr));
                conObj.cmdObj.Connection.Open();
                conObj.drObj = conObj.cmdObj.ExecuteReader();
                if (conObj.drObj.Read()) salesAnalysisModel.HighestLineTotal = Convert.ToDecimal(conObj.drObj["Linetot"]);
                conObj.cmdObj.Dispose();
                conObj.cmdObj = new SqlCommand("SELECT ProductID  FROM Product WHERE Name=@name", new SqlConnection(dbObj.conStr));
                conObj.cmdObj.Parameters.AddWithValue("@name", "Front Brakes");
                conObj.cmdObj.Connection.Open();
                conObj.drObj = conObj.cmdObj.ExecuteReader();
                if (conObj.drObj.Read()) {
                    string itemId = conObj.drObj["ProductID"]?.ToString() ?? default;
                    if (itemId != null) {
                        conObj.cmdObj.Dispose();
                        conObj.cmdObj = new SqlCommand("SELECT SUM(LineTotal) AS BrakeTot FROM SalesOrder WHERE ProductID=@pID ", new SqlConnection(dbObj.conStr));
                        conObj.cmdObj.Parameters.AddWithValue("@pID",itemId);
                        conObj.cmdObj.Connection.Open();
                        conObj.drObj = conObj.cmdObj.ExecuteReader();
                        if(conObj.drObj.Read()) salesAnalysisModel.FrontBrakesSalesTotal= Convert.ToDecimal(conObj.drObj["BrakeTot"]);
                    }
                }
            } catch { } finally {
                if (conObj.cmdObj != null && conObj.cmdObj.Connection != null) conObj.cmdObj.Connection.Close();
                conObj = null;
            }
            ViewBag.vData = salesAnalysisModel;
            return View();
        }

    }
}

AdventureWorksSales.Web/Controllers/ProductCategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.SqlClient;
using AdventureWorksSales.Web.Models;

namespace AdventureWorksSales.Web.Controllers
{
    public class ProductCategoryController : Controller
    {
        // GET: ProductCategory
        dbObj conObj = new dbObj();
        ProductCategoryModel ProdCatModel;
        List<ProductCategoryModel> AllProductCategory;
        public ActionResult Index() {
           AllProductCategory = new List<ProductCategoryModel>();

            try {
                conObj.cmdObj = new SqlCommand("SELECT* FROM ProductCategory", new SqlConnection(dbObj.conStr));
                conObj.cmdObj.Connection.Open();
                conObj.drObj = conObj.cmdObj.ExecuteReader();
                while (conObj.drObj.Read()) {
                    ProdCatModel = new ProductCategoryModel {
                        Name = conObj.drObj["Name"].ToString(),
                        ProductCategoryID = Convert.ToInt16(conObj.drObj["ProductCategoryID"]),
                        ModifiedDate = Convert.ToDateTime(conObj.drObj["ModifiedDate"])
                    };
                    AllProductCategory.Add(ProdCatModel);   
                }
            } catch { } finally {
                if (conObj.cmdObj != null && conObj.cmdObj.Connection != null) conObj.cmdObj.Connection.Close();
                conObj = null;
            }
            ViewBag.vData = AllProductCategory;
            return View();
        }

        [HttpPost]
        public ActionResult Addnew(string proCatName) {
            if (!string.IsNullOrEmpty(proCatName)) {
                try {
                    conObj.cmdObj = new SqlCommand("INSERT INTO ProductCategory(Name,rowguid,ModifiedDate)VALUES(@Name,@rowguid,@ModifiedDate)", new SqlConnection(dbObj.conStr));
                    conObj.cmdObj.Parameters.AddWithValue("@Name", proCatName.Trim());
                    conObj.cmdObj.Parameters.AddWithValue("@rowguid",Guid.NewGuid());
                    conObj.cmdObj.Parameters.AddWithValue("@ModifiedDate",DateTime.Now);
                    conObj.cmdObj.Connection.Open();
                    conObj.cmdObj.ExecuteNonQuery();                    
                } catch { } finally {
                    if (conObj.cmdObj != null && conObj.cmdObj.Connection != null) conObj.cmdObj.Connection.Close();
                    conObj = null;
                }
            }
            return RedirectToAction("Index");
        }

        
        public ActionResult Edit(string id) {
            if (!string.IsNullOrEmpty(id)) {
                try {
                    conObj.cmdObj = new SqlCommand("SELECT Name FROM ProductCategory WHERE ProductCategoryID=@ProductCategoryID", new SqlConnection(dbObj.conStr));
                    conObj.cmdObj.Parameters.AddWithValue("@ProductCategoryID", id.Trim());
                    conObj.cmdObj.Connection.Open();
                    conObj.drObj = conObj.cmdObj.ExecuteReader();
                    if (conObj.drObj.Read()) ViewBag.vData = conObj.drObj["Name"].ToString()+"-"+id;
                } catch { } finally {
                    if (conObj.cmdObj != null && conObj.cmdObj.Connection != null) conObj.cmdObj.Connection.Close();
                    conObj = null;
                }
                return View();                
            }else return RedirectToAction("Index");
        }
        [HttpPost]
        public ActionResult Update( string proCatName,string editId) {
            if (!string.IsNullOrEmpty(proCatName)) {
                try {
                    conObj.cmdObj = new SqlCommand("UPDATE ProductCategory SET Name = @Name, ModifiedDate=@ModifiedDate WHERE ProductCategoryID=@ProductCategoryID; ", new SqlConnection(dbObj.conStr));
                    conObj.cmdObj.Parameters.AddWithValue("@Name", proCatName.Trim());
                    conObj.cmdObj.Parameters.AddWithValue("@ProductCategoryID",editId);
                    conObj.cmdObj.Parameters.AddWithValue("@ModifiedDate", DateTime.Now);
                    conObj.cmdObj.Connection.Open();
                    conObj.cmdObj.ExecuteNonQuery();
                } catch { } finally {
                    if (conObj.cmdObj != null && conObj.cmdObj.Connection != null) conObj.cmdObj.Connection.Close();
                    conObj = null;
                }
            }
            return RedirectToAction("Index");
        }
    }
}

AdventureWorksSales.Web/Views/Home/Index.cshtml
@using AdventureWorksSales.Web.Models;

@{
    ViewBag.Title = "Home Page";
    SalesAnalysisModel inModel = ViewBag.vData; 
}

<div class="jumbotron">
    <h1>SALES ANALYSIS</h1>
    <p class="lead">This application is for test purposes and do not reflect actual data of any company or organization</p>
</div>

<div class="row">
    <div class="col-md-12">
        <h3><i>Below, sales figures are represented in US Dollars</i></h3>
        <hr>
    </div>
</div>
<div class="row">
    <div class="col-md-4">
        <h2>Total orders</h2>
        <p class="sales">
           @inModel.TotalOrders
        </p>
    </div>
    <div class="col-md-4">
        <h2>Highest line total</h2>
        <p class="sales" style="font-size:55px;">
            @inModel.HighestLineTotal
        </p>
    </div>
    <div class="col-md-4">
        <h2>Front Brakes sales total</h2>
        <p class="sales">
            @inModel.FrontBrakesSalesTotal
        </p>
    </div>
</div>

AdventureWorksSales.Web/Views/ProductCategory/Edit.cshtml
@{
    ViewBag.Title = "Edit";
    string eData = ViewBag.vData;
}

<h2>Edit this Product Category</h2>

<form action="/ProductCategory/Update" method="post">
    <div class="form-group">
        <label for="email">Name:</label>
        <input type="text" class="form-control" name="proCatName" placeholder="@if(eData!= null) {@eData.Split('-')[0]} " required>
        <input type="hidden" name="editId" value="@if(eData!= null) {@eData.Split('-')[1]}" />
    </div>
    <button type="submit" name="" class="btn btn-primary">Update</button>
</form>

AdventureWorksSales.Web/Views/ProductCategory/Index.cshtml
@using AdventureWorksSales.Web.Models
@{
    ViewBag.Title = "Index";
    List<ProductCategoryModel> AllProductCategories = ViewBag.vData;
}

<h2>Product Categories</h2>


<div style="border:dotted;padding:8px;">
    <form action="/ProductCategory/AddNew" method="post">
        <div class="form-group">
            <label for="email">New Category:</label>
            <input type="text" class="form-control" name="proCatName" placeholder="Category name" required>
        </div>
        <button type="submit" name="" class="btn btn-primary">Add Category</button>
    </form>
</div>
<br />
<p>List of all product categories. You can click the Edit button from the list to Edit the Corresponding Product Category.</p>

<table class="table">
    <thead>
        <tr>
            <th>#</th>
            <th>Category Names</th>
            <th>Last Modified Date</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (ProductCategoryModel prodCat in AllProductCategories) {
            <tr>
                <td>@prodCat.ProductCategoryID</td>
                <td>@prodCat.Name</td>
                <td>@prodCat.ModifiedDate</td>
                <td><a href="/ProductCategory/Edit/@prodCat.ProductCategoryID" class="btn btn-primary">Edit</a></td>
            </tr>
        }

    </tbody>
</table>

AdventureWorksSales.Web/Views/Shared/_Layout.cshtml
@{ string applicationName = "Adventure Works Portal";}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - @applicationName</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink(applicationName, "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Product Categories", "Index", "ProductCategory")</li>
                    <li>@Html.ActionLink("Products", "Index", "Product")</li>
                    <li>@Html.ActionLink("Sales Order", "Index", "SalesOrder")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - @applicationName</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>